/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface AccessToken {
  /** @nullable */
  claims?: string[] | null;
  /** @nullable */
  token?: string | null;
  expiration?: string;
  /** @nullable */
  refreshToken?: string | null;
}
