/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccountContactDto } from "./accountContactDto";

/**
 * @nullable
 */
export type AccountContactDtoIDataResultData = AccountContactDto | null;
