/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface AccountContactDto {
  /** @nullable */
  readonly accountId?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  readonly profileQrCodeLink?: string | null;
  /** @nullable */
  photoUrl?: string | null;
  /** @nullable */
  publicKey?: string | null;
}
