/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccountDto } from "./accountDto";

export interface AccountDtoListPaginatedResult {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: AccountDto[] | null;
  pageNumber?: number;
  pageSize?: number;
  totalPages?: number;
  totalRecords?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
}
