/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccountProfileDtoLicense } from "./accountProfileDtoLicense";

export interface AccountProfileDto {
  /** @nullable */
  readonly accountId?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  readonly profileQrCodeLink?: string | null;
  voiceTransformer?: boolean;
  enableScreenShots?: boolean;
  enableTor?: boolean;
  enablePushNotifications?: boolean;
  enableReadReceipt?: boolean;
  autoDeleteMessagesHours?: number;
  askSpacePassword?: number;
  enableOnlineStatus?: boolean;
  enablePrivateNotes?: boolean;
  deleteButton?: boolean;
  /** @nullable */
  photoUrl?: string | null;
  /** @nullable */
  license?: AccountProfileDtoLicense;
}
