/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccountDtoDeviceInformation } from "./accountDtoDeviceInformation";
import type { AccountStatus } from "./accountStatus";
import type { AccountType } from "./accountType";

export interface AccountDto {
  /** @nullable */
  readonly accountId?: string | null;
  accountType?: AccountType;
  accountStatus?: AccountStatus;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  licenseCode?: string | null;
  /** @nullable */
  language?: string | null;
  voiceTransformer?: boolean;
  enableScreenShots?: boolean;
  enableTor?: boolean;
  enablePushNotifications?: boolean;
  enableReadReceipt?: boolean;
  autoDeleteMessagesHours?: number;
  askSpacePassword?: number;
  enableOnlineStatus?: boolean;
  enablePrivateNotes?: boolean;
  deleteButton?: boolean;
  /** @nullable */
  photoUrl?: string | null;
  /** @nullable */
  deviceInformation?: AccountDtoDeviceInformation;
  createdAt?: string;
}
