/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface AccountSearchDto {
  /** @nullable */
  username?: string | null;
  /** @nullable */
  photoUrl?: string | null;
  /** @nullable */
  publicKey?: string | null;
}
