/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface AccountSettingsCommandRequest {
  voiceTransformer?: boolean;
  enableScreenShots?: boolean;
  enableTor?: boolean;
  enablePushNotifications?: boolean;
  enableReadReceipt?: boolean;
  autoDeleteMessagesHours?: number;
  askSpacePassword?: number;
  enableOnlineStatus?: boolean;
  enablePrivateNotes?: boolean;
  deleteButton?: boolean;
}
