/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccountProfileDtoIDataResultData } from "./accountProfileDtoIDataResultData";
import type { ResultMessage } from "./resultMessage";

export interface AccountProfileDtoIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: AccountProfileDtoIDataResultData;
}
