/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccountSearchDto } from "./accountSearchDto";
import type { ResultMessage } from "./resultMessage";

export interface AccountSearchDtoListPaginatedResult {
  success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  data?: AccountSearchDto[] | null;
  pageNumber?: number;
  pageSize?: number;
  totalPages?: number;
  totalRecords?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
}
