/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { LicenseProfileDto } from "./licenseProfileDto";

/**
 * @nullable
 */
export type AccountProfileDtoLicense = LicenseProfileDto | null;
