/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccountProfileDtoIDataResultData } from "./accountProfileDtoIDataResultData";

export interface AccountProfileDtoIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: string[] | null;
  /** @nullable */
  readonly data?: AccountProfileDtoIDataResultData;
}
