/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccountDetailDtoIDataResultData } from "./accountDetailDtoIDataResultData";
import type { ResultMessage } from "./resultMessage";

export interface AccountDetailDtoIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: AccountDetailDtoIDataResultData;
}
