/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export type AccountStatus = (typeof AccountStatus)[keyof typeof AccountStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountStatus = {
  Inactive: "Inactive",
  Active: "Active",
} as const;
