/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccountDetailDtoCurrentSubscription } from "./accountDetailDtoCurrentSubscription";
import type { AccountDetailDtoDeviceInformation } from "./accountDetailDtoDeviceInformation";
import type { AccountStatus } from "./accountStatus";
import type { AccountType } from "./accountType";
import type { LicenseDto } from "./licenseDto";

export interface AccountDetailDto {
  /** @nullable */
  readonly accountId?: string | null;
  /** @nullable */
  licenseCode?: string | null;
  accountStatus?: AccountStatus;
  accountType?: AccountType;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  language?: string | null;
  /** @nullable */
  deviceToken?: string | null;
  voiceTransformer?: boolean;
  enableScreenShots?: boolean;
  enableTor?: boolean;
  enablePushNotifications?: boolean;
  enableReadReceipt?: boolean;
  autoDeleteMessagesHours?: number;
  askSpacePassword?: number;
  enableOnlineStatus?: boolean;
  enablePrivateNotes?: boolean;
  deleteButton?: boolean;
  isLoggedIn?: boolean;
  twoFactorEnabled?: boolean;
  /** @nullable */
  last2FAVerifiedAt?: string | null;
  createdAt?: string;
  /** @nullable */
  photoUrl?: string | null;
  /** @nullable */
  deviceInformation?: AccountDetailDtoDeviceInformation;
  /** @nullable */
  currentSubscription?: AccountDetailDtoCurrentSubscription;
  /** @nullable */
  licenseHistory?: LicenseDto[] | null;
}
