/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccountDetailDto } from "./accountDetailDto";

/**
 * @nullable
 */
export type AccountDetailDtoIDataResultData = AccountDetailDto | null;
