/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface AddMessageToTicketCommandRequest {
  /** @nullable */
  ticketId?: string | null;
  /** @nullable */
  content?: string | null;
}
