/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AdminLoginCommandResult } from "./adminLoginCommandResult";

/**
 * @nullable
 */
export type AdminLoginCommandResultIDataResultData =
  AdminLoginCommandResult | null;
