/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AdminAccountDto } from "./adminAccountDto";

/**
 * @nullable
 */
export type AdminLoginCommandResultAccount = AdminAccountDto | null;
