/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ResultMessage } from "./resultMessage";
import type { AdminLoginCommandResultIDataResultData } from "./adminLoginCommandResultIDataResultData";

export interface AdminLoginCommandResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: AdminLoginCommandResultIDataResultData;
}
