/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AdminLoginCommandResultIDataResultData } from "./adminLoginCommandResultIDataResultData";

export interface AdminLoginCommandResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: string[] | null;
  /** @nullable */
  readonly data?: AdminLoginCommandResultIDataResultData;
}
