/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AdminLoginCommandResultAccessToken } from "./adminLoginCommandResultAccessToken";
import type { AdminLoginCommandResultAccount } from "./adminLoginCommandResultAccount";

export interface AdminLoginCommandResult {
  /** @nullable */
  accessToken?: AdminLoginCommandResultAccessToken;
  /** @nullable */
  account?: AdminLoginCommandResultAccount;
}
