/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { CallingType } from "./callingType";

export interface AnswerGroupCallCommandRequest {
  /** @nullable */
  callId?: string | null;
  /** @nullable */
  groupName?: string | null;
  answerType?: CallingType;
  /** @nullable */
  answer?: string | null;
}
