/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { CallingType } from "./callingType";

export interface AnswerCallCommandRequest {
  /** @nullable */
  callerUsername?: string | null;
  answerType?: CallingType;
  /** @nullable */
  answer?: string | null;
}
