/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { BuyLicenseCommandResultIDataResultData } from "./buyLicenseCommandResultIDataResultData";

export interface BuyLicenseCommandResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: string[] | null;
  /** @nullable */
  readonly data?: BuyLicenseCommandResultIDataResultData;
}
