/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface BuyLicenseCommandRequest {
  /** @nullable */
  username?: string | null;
  /** @nullable */
  deviceId?: string | null;
  /** @nullable */
  subscriptionPlanId?: string | null;
  /** @nullable */
  transactionId?: string | null;
  freeTrial?: boolean;
}
