/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { CallingType } from "./callingType";

export interface CallUserCommandRequest {
  /** @nullable */
  targetUsername?: string | null;
  callingType?: CallingType;
  /** @nullable */
  offer?: string | null;
}
