/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { CallingDtoListPaginatedResult } from "./callingDtoListPaginatedResult";

/**
 * @nullable
 */
export type CallingDtoListPaginatedResultIDataResultData =
  CallingDtoListPaginatedResult | null;
