/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { CallingDto } from "./callingDto";
import type { ResultMessage } from "./resultMessage";

export interface CallingDtoListPaginatedResult {
  success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  data?: CallingDto[] | null;
  pageNumber?: number;
  pageSize?: number;
  totalPages?: number;
  totalRecords?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
}
