/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { CallingDto } from "./callingDto";

/**
 * @nullable
 */
export type CallingDtoIDataResultData = CallingDto | null;
