/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { CallingType } from "./callingType";

export interface CallingDto {
  /** @nullable */
  readonly callingId?: string | null;
  callingType?: CallingType;
  /** @nullable */
  caller?: string | null;
  /** @nullable */
  targets?: string[] | null;
  /** @nullable */
  offer?: string | null;
  isGroupCalling?: boolean;
  startedAt?: string;
  /** @nullable */
  endedAt?: string | null;
}
