/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccountStatus } from "./accountStatus";

export interface ChangeAccountStatusCommandRequest {
  /** @nullable */
  accountId?: string | null;
  status?: AccountStatus;
}
