/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { InvoiceStatus } from "./invoiceStatus";

export interface ChangeInvoiceStatusCommandRequest {
  /** @nullable */
  id?: string | null;
  status?: InvoiceStatus;
}
