/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { TicketStatus } from "./ticketStatus";

export interface ChangeTicketStatusCommandRequest {
  /** @nullable */
  id?: string | null;
  status?: TicketStatus;
}
