/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { LicenseStatus } from "./licenseStatus";

export interface ChangeLicenseStatusCommandRequest {
  /** @nullable */
  id?: string | null;
  status?: LicenseStatus;
}
