/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ChatDtoListPaginatedResult } from "./chatDtoListPaginatedResult";

/**
 * @nullable
 */
export type ChatDtoListPaginatedResultIDataResultData =
  ChatDtoListPaginatedResult | null;
