/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ChatDtoListPaginatedResultIDataResultData } from "./chatDtoListPaginatedResultIDataResultData";
import type { ResultMessage } from "./resultMessage";

export interface ChatDtoListPaginatedResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: ChatDtoListPaginatedResultIDataResultData;
}
