/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ChatDtoContact } from "./chatDtoContact";

export interface ChatDto {
  /** @nullable */
  readonly chatId?: string | null;
  isGroupChat?: boolean;
  /** @nullable */
  groupName?: string | null;
  /** @nullable */
  groupAdminAccount?: string | null;
  /** @nullable */
  groupAdminUsername?: string | null;
  /** @nullable */
  lastMessageTime?: string | null;
  /** @nullable */
  groupKey?: string | null;
  /** @nullable */
  groupNonce?: string | null;
  /** @nullable */
  readonly groupAccountCount?: string | null;
  /** @nullable */
  contact?: ChatDtoContact;
  unreadMessagesCount?: number;
}
