/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ChatDtoContact } from "./chatDtoContact";

export interface ChatDto {
  /** @nullable */
  readonly chatId?: string | null;
  isGroupChat?: boolean;
  /** @nullable */
  groupName?: string | null;
  /** @nullable */
  readonly groupAdminAccount?: string | null;
  /** @nullable */
  lastMessageTime?: string | null;
  /** @nullable */
  contact?: ChatDtoContact;
  unreadMessagesCount?: number;
}
