/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ContactDto } from "./contactDto";

/**
 * @nullable
 */
export type ChatDtoContact = ContactDto | null;
