/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ContactDto } from "./contactDto";
import type { ResultMessage } from "./resultMessage";

export interface ContactDtoListIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: readonly ContactDto[] | null;
}
