/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface ContactDto {
  /** @nullable */
  readonly contactId?: string | null;
  /** @nullable */
  nickname?: string | null;
  /** @nullable */
  contactUsername?: string | null;
  /** @nullable */
  publicKey?: string | null;
  isBlocked?: boolean;
  /** @nullable */
  chats?: string[] | null;
}
