/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface ContactDto {
  /** @nullable */
  readonly contactId?: string | null;
  /** @nullable */
  nickname?: string | null;
  /** @nullable */
  chatId?: string | null;
  /** @nullable */
  contactAccountId?: string | null;
}
