/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { CreateAccountCommandRequestAccountType } from "./createAccountCommandRequestAccountType";

export interface CreateAccountCommandRequest {
  /** @nullable */
  licenseCode?: string | null;
  /** @nullable */
  accountType?: CreateAccountCommandRequestAccountType;
  /** @nullable */
  transactionId?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  confirmPassword?: string | null;
}
