/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface CreateAccountCommandResult {
  /** @nullable */
  securityPhrases?: string[] | null;
}
