/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { FaqCategory } from "./faqCategory";

export interface CreateFaqCommandRequest {
  /** @nullable */
  faqQuestion?: string | null;
  /** @nullable */
  faqAnswer?: string | null;
  category?: FaqCategory;
}
