/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface CreateTicketCommandRequest {
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  content?: string | null;
}
