/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface CreateLanguageCommand {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  code?: string | null;
}
