/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { CreateAccountCommandResult } from "./createAccountCommandResult";

/**
 * @nullable
 */
export type CreateAccountCommandResultIDataResultData =
  CreateAccountCommandResult | null;
