/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { EncryptedGroupKey } from "./encryptedGroupKey";

export interface CreateChatCommandRequest {
  /** @nullable */
  groupName?: string | null;
  /** @nullable */
  usernames?: string[] | null;
  isGroupChat?: boolean;
  /** @nullable */
  encryptedGroupKeys?: EncryptedGroupKey[] | null;
}
