/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface CreateChatCommandRequest {
  /** @nullable */
  groupName?: string | null;
  /** @nullable */
  accountIds?: string[] | null;
  isGroupChat?: boolean;
}
