/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { CreateAccountCommandResultIDataResultData } from "./createAccountCommandResultIDataResultData";
import type { ResultMessage } from "./resultMessage";

export interface CreateAccountCommandResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: CreateAccountCommandResultIDataResultData;
}
