/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface DeviceInformation {
  /** @nullable */
  deviceName?: string | null;
  /** @nullable */
  deviceModelName?: string | null;
  /** @nullable */
  deviceBrand?: string | null;
  /** @nullable */
  deviceManufacturer?: string | null;
  /** @nullable */
  deviceType?: string | null;
  /** @nullable */
  osName?: string | null;
  /** @nullable */
  osVersion?: string | null;
  /** @nullable */
  appVersion?: string | null;
  /** @nullable */
  appBuildNumber?: string | null;
}
