/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface EncryptedGroupKey {
  /** @nullable */
  username?: string | null;
  /** @nullable */
  groupKey?: string | null;
  /** @nullable */
  nonce?: string | null;
}
