/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export type EntityStatus = (typeof EntityStatus)[keyof typeof EntityStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntityStatus = {
  Active: "Active",
  Passive: "Passive",
  Deleted: "Deleted",
} as const;
