/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ObjectId } from "./objectId";
import type { EntityStatus } from "./entityStatus";
import type { FaqCategory } from "./faqCategory";

export interface Faq {
  id?: ObjectId;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  deletedAt?: string | null;
  status?: EntityStatus;
  /** @nullable */
  faqQuestion?: string | null;
  /** @nullable */
  faqAnswer?: string | null;
  category?: FaqCategory;
}
