/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { EntityStatus } from "./entityStatus";
import type { FaqCategory } from "./faqCategory";
import type { FaqDeletedBy } from "./faqDeletedBy";
import type { FaqUpdatedBy } from "./faqUpdatedBy";
import type { ObjectId } from "./objectId";

export interface Faq {
  id?: ObjectId;
  createdAt?: string;
  createdBy?: ObjectId;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  updatedBy?: FaqUpdatedBy;
  /** @nullable */
  deletedAt?: string | null;
  /** @nullable */
  deletedBy?: FaqDeletedBy;
  status?: EntityStatus;
  /** @nullable */
  faqQuestion?: string | null;
  /** @nullable */
  faqAnswer?: string | null;
  category?: FaqCategory;
}
