/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ResultMessage } from "./resultMessage";
import type { FaqDto } from "./faqDto";

export interface FaqDtoListPaginatedResult {
  success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  data?: FaqDto[] | null;
  pageNumber?: number;
  pageSize?: number;
  totalPages?: number;
  totalRecords?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
}
