/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { FaqIDataResultData } from "./faqIDataResultData";
import type { ResultMessage } from "./resultMessage";

export interface FaqIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: FaqIDataResultData;
}
