/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { LicenseStatus } from "./licenseStatus";

export type GetApiLicensesListParams = {
  licenseCode?: string;
  status?: LicenseStatus;
  onlyFreeLicenses?: boolean;
  pageNumber?: number;
  pageSize?: number;
};
