/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { InvoiceStatus } from "./invoiceStatus";

export type GetApiInvoicesListParams = {
  query?: string;
  status?: InvoiceStatus;
  pageNumber?: number;
  pageSize?: number;
};
