/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { TicketStatus } from "./ticketStatus";

export type GetApiTicketsListParams = {
  username?: string;
  licenseCode?: string;
  status?: TicketStatus;
  pageNumber?: number;
  pageSize?: number;
};
