/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { TimeFrame } from "./timeFrame";

export type GetApiStatisticsGetTotalChatsParams = {
  timeFrame?: TimeFrame;
};
