/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { FaqCategory } from "./faqCategory";

export type GetApiFaqsListParams = {
  query?: string;
  category?: FaqCategory;
  pageNumber?: number;
  pageSize?: number;
};
