/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export type GetApiChatsGroupMessagesParams = {
  chatId?: string;
  pageNumber?: number;
  pageSize?: number;
};
