/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccountStatus } from "./accountStatus";
import type { AccountType } from "./accountType";

export type GetApiAccountListParams = {
  status?: AccountStatus;
  accountType?: AccountType;
  query?: string;
  startDate?: string;
  endDate?: string;
  pageNumber?: number;
  pageSize?: number;
};
