/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export type GetApiChatsListParams = {
  isGroupChat?: boolean;
  isArchivedChat?: boolean;
  pageNumber?: number;
  pageSize?: number;
};
