/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { MessageDto } from "./messageDto";
import type { ContactDto } from "./contactDto";

export interface GetGroupMessagesQueryResult {
  /** @nullable */
  messages?: MessageDto[] | null;
  /** @nullable */
  contacts?: ContactDto[] | null;
}
