/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { GetGroupMessagesQueryResultIDataResultData } from "./getGroupMessagesQueryResultIDataResultData";

export interface GetGroupMessagesQueryResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: string[] | null;
  /** @nullable */
  readonly data?: GetGroupMessagesQueryResultIDataResultData;
}
