/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ContactDto } from "./contactDto";
import type { GetGroupMessagesQueryResultMessages } from "./getGroupMessagesQueryResultMessages";

export interface GetGroupMessagesQueryResult {
  /** @nullable */
  messages?: GetGroupMessagesQueryResultMessages;
  /** @nullable */
  contacts?: ContactDto[] | null;
}
