/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { MessageDtoListPaginatedResult } from "./messageDtoListPaginatedResult";

/**
 * @nullable
 */
export type GetGroupMessagesQueryResultMessages =
  MessageDtoListPaginatedResult | null;
