/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { GetGroupMessagesQueryResultIDataResultData } from "./getGroupMessagesQueryResultIDataResultData";
import type { ResultMessage } from "./resultMessage";

export interface GetGroupMessagesQueryResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: GetGroupMessagesQueryResultIDataResultData;
}
