/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { GetMessagesQueryResult } from "./getMessagesQueryResult";

/**
 * @nullable
 */
export type GetMessagesQueryResultIDataResultData =
  GetMessagesQueryResult | null;
