/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { GetMessagesQueryResultMessages } from "./getMessagesQueryResultMessages";

export interface GetMessagesQueryResult {
  isScreenShotEnable?: boolean;
  /** @nullable */
  messages?: GetMessagesQueryResultMessages;
}
