/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { MessageDtoListPaginatedResult } from "./messageDtoListPaginatedResult";

/**
 * @nullable
 */
export type GetMessagesQueryResultMessages =
  MessageDtoListPaginatedResult | null;
