/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { MessageDto } from "./messageDto";

export interface GetMessagesQueryResult {
  isScreenShotEnable?: boolean;
  /** @nullable */
  messages?: MessageDto[] | null;
}
