/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ResultMessage } from "./resultMessage";
import type { GetMessagesQueryResultIDataResultData } from "./getMessagesQueryResultIDataResultData";

export interface GetMessagesQueryResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: GetMessagesQueryResultIDataResultData;
}
