/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ImportAccountProfileCommandResultAccessToken } from "./importAccountProfileCommandResultAccessToken";
import type { ImportAccountProfileCommandResultAccount } from "./importAccountProfileCommandResultAccount";

export interface ImportAccountProfileCommandResult {
  /** @nullable */
  accessToken?: ImportAccountProfileCommandResultAccessToken;
  /** @nullable */
  account?: ImportAccountProfileCommandResultAccount;
  /** @nullable */
  licenseExpiryDate?: string | null;
}
