/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface InviteToGroupCommandRequest {
  /** @nullable */
  chatId?: string | null;
  /** @nullable */
  usernames?: string[] | null;
}
