/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { InvoiceLine } from "./invoiceLine";
import type { InvoiceStatus } from "./invoiceStatus";

export interface InvoiceDetailDto {
  /** @nullable */
  readonly invoiceId?: string | null;
  invoiceStatus?: InvoiceStatus;
  /** @nullable */
  invoiceNumber?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  licenseCode?: string | null;
  /** @nullable */
  invoiceLines?: InvoiceLine[] | null;
  /** @nullable */
  currency?: string | null;
  totalAmount?: number;
  issueDate?: string;
  dueDate?: string;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
}
