/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { Invoice } from "./invoice";

/**
 * @nullable
 */
export type InvoiceIDataResultData = Invoice | null;
