/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { InvoiceDetailDto } from "./invoiceDetailDto";

/**
 * @nullable
 */
export type InvoiceDetailDtoIDataResultData = InvoiceDetailDto | null;
