/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { EntityStatus } from "./entityStatus";
import type { InvoiceDeletedBy } from "./invoiceDeletedBy";
import type { InvoiceLine } from "./invoiceLine";
import type { InvoiceStatus } from "./invoiceStatus";
import type { InvoiceUpdatedBy } from "./invoiceUpdatedBy";
import type { ObjectId } from "./objectId";

export interface Invoice {
  id?: ObjectId;
  createdAt?: string;
  createdBy?: ObjectId;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  updatedBy?: InvoiceUpdatedBy;
  /** @nullable */
  deletedAt?: string | null;
  /** @nullable */
  deletedBy?: InvoiceDeletedBy;
  status?: EntityStatus;
  invoiceStatus?: InvoiceStatus;
  /** @nullable */
  invoiceNumber?: string | null;
  accountId?: ObjectId;
  /** @nullable */
  invoiceLines?: InvoiceLine[] | null;
  /** @nullable */
  currency?: string | null;
  readonly totalAmount?: number;
  issueDate?: string;
  dueDate?: string;
}
