/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export type InvoiceStatus = (typeof InvoiceStatus)[keyof typeof InvoiceStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceStatus = {
  Issued: "Issued",
  Paid: "Paid",
  Cancelled: "Cancelled",
} as const;
