/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ObjectId } from "./objectId";
import type { EntityStatus } from "./entityStatus";
import type { InvoiceStatus } from "./invoiceStatus";
import type { InvoiceLine } from "./invoiceLine";

export interface Invoice {
  id?: ObjectId;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  deletedAt?: string | null;
  status?: EntityStatus;
  invoiceStatus?: InvoiceStatus;
  /** @nullable */
  invoiceNumber?: string | null;
  accountId?: ObjectId;
  /** @nullable */
  invoiceLines?: InvoiceLine[] | null;
  /** @nullable */
  currency?: string | null;
  readonly totalAmount?: number;
  issueDate?: string;
  dueDate?: string;
}
