/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { InvoiceIDataResultData } from "./invoiceIDataResultData";
import type { ResultMessage } from "./resultMessage";

export interface InvoiceIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: InvoiceIDataResultData;
}
