/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { InvoiceStatus } from "./invoiceStatus";
import type { InvoiceLine } from "./invoiceLine";

export interface InvoiceDto {
  /** @nullable */
  readonly invoiceId?: string | null;
  invoiceStatus?: InvoiceStatus;
  /** @nullable */
  invoiceNumber?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  licenseCode?: string | null;
  /** @nullable */
  invoiceLines?: InvoiceLine[] | null;
  /** @nullable */
  currency?: string | null;
  totalAmount?: number;
  issueDate?: string;
  dueDate?: string;
  createdAt?: string;
}
