/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface InvoiceLine {
  /** @nullable */
  productCode?: string | null;
  /** @nullable */
  description?: string | null;
  unitPrice?: number;
  quantity?: number;
  taxRate?: number;
}
