/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ObjectId } from "./objectId";
import type { EntityStatus } from "./entityStatus";

export interface Language {
  id?: ObjectId;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  deletedAt?: string | null;
  status?: EntityStatus;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  code?: string | null;
}
