/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { LicenseDetailDto } from "./licenseDetailDto";

/**
 * @nullable
 */
export type LicenseDetailDtoIDataResultData = LicenseDetailDto | null;
