/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { SubscriptionDto } from "./subscriptionDto";

/**
 * @nullable
 */
export type LicenseDetailDtoSubscriptionPlan = SubscriptionDto | null;
