/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { LicenseDetailDtoIDataResultData } from "./licenseDetailDtoIDataResultData";

export interface LicenseDetailDtoIDataResult {
  readonly success?: boolean;
  /** @nullable */
  readonly message?: string | null;
  /** @nullable */
  readonly data?: LicenseDetailDtoIDataResultData;
}
