/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export type LicenseStatus = (typeof LicenseStatus)[keyof typeof LicenseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseStatus = {
  Initialized: "Initialized",
  Active: "Active",
  Inactive: "Inactive",
  Expired: "Expired",
} as const;
