/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { LicenseDetailDtoIDataResultData } from "./licenseDetailDtoIDataResultData";
import type { ResultMessage } from "./resultMessage";

export interface LicenseDetailDtoIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: LicenseDetailDtoIDataResultData;
}
