/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { LicenseStatus } from "./licenseStatus";
import type { LicenseProfileDtoSubscriptionPlan } from "./licenseProfileDtoSubscriptionPlan";

export interface LicenseProfileDto {
  /** @nullable */
  readonly licenseId?: string | null;
  /** @nullable */
  licenseCode?: string | null;
  licenseStatus?: LicenseStatus;
  /** @nullable */
  deviceId?: string | null;
  /** @nullable */
  subscriptionPlan?: LicenseProfileDtoSubscriptionPlan;
  /** @nullable */
  expirationDate?: string | null;
}
