/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { LicenseDtoAccount } from "./licenseDtoAccount";
import type { LicenseDtoSubscriptionPlan } from "./licenseDtoSubscriptionPlan";
import type { LicenseStatus } from "./licenseStatus";

export interface LicenseDto {
  /** @nullable */
  readonly licenseId?: string | null;
  /** @nullable */
  licenseCode?: string | null;
  licenseStatus?: LicenseStatus;
  /** @nullable */
  account?: LicenseDtoAccount;
  /** @nullable */
  deviceId?: string | null;
  /** @nullable */
  subscriptionPlan?: LicenseDtoSubscriptionPlan;
  /** @nullable */
  invoiceId?: string | null;
  /** @nullable */
  expirationDate?: string | null;
  createdAt?: string;
}
