/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { LicenseStatus } from "./licenseStatus";
import type { LicenseDetailDtoAccount } from "./licenseDetailDtoAccount";
import type { LicenseDetailDtoSubscriptionPlan } from "./licenseDetailDtoSubscriptionPlan";
import type { Transaction } from "./transaction";

export interface LicenseDetailDto {
  /** @nullable */
  readonly licenseId?: string | null;
  /** @nullable */
  licenseCode?: string | null;
  licenseStatus?: LicenseStatus;
  /** @nullable */
  account?: LicenseDetailDtoAccount;
  /** @nullable */
  deviceId?: string | null;
  /** @nullable */
  subscriptionPlan?: LicenseDetailDtoSubscriptionPlan;
  expirationDate?: string;
  /** @nullable */
  transactions?: Transaction[] | null;
}
