/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { SubscriptionDto } from "./subscriptionDto";

/**
 * @nullable
 */
export type LicenseDtoSubscriptionPlan = SubscriptionDto | null;
