/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ResultMessage } from "./resultMessage";
import type { LicenseDto } from "./licenseDto";

export interface LicenseDtoListPaginatedResult {
  success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  data?: LicenseDto[] | null;
  pageNumber?: number;
  pageSize?: number;
  totalPages?: number;
  totalRecords?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
}
