/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ObjectId } from "./objectId";

export interface LogDto {
  id?: ObjectId;
  /** @nullable */
  level?: string | null;
  /** @nullable */
  exceptionMessage?: string | null;
  timeStamp?: string;
  /** @nullable */
  user?: string | null;
  /** @nullable */
  value?: string | null;
  /** @nullable */
  type?: string | null;
}
