/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { LoginCommandResultIDataResultData } from "./loginCommandResultIDataResultData";

export interface LoginCommandResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  readonly message?: string | null;
  /** @nullable */
  readonly data?: LoginCommandResultIDataResultData;
}
