/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { LoginCommandResult } from "./loginCommandResult";

/**
 * @nullable
 */
export type LoginCommandResultIDataResultData = LoginCommandResult | null;
