/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { LoginCommandResultAccessToken } from "./loginCommandResultAccessToken";
import type { LoginCommandResultAccount } from "./loginCommandResultAccount";

export interface LoginCommandResult {
  /** @nullable */
  accessToken?: LoginCommandResultAccessToken;
  /** @nullable */
  account?: LoginCommandResultAccount;
  /** @nullable */
  licenseExpiryDate?: string | null;
}
