/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ResultMessage } from "./resultMessage";
import type { LoginCommandResultIDataResultData } from "./loginCommandResultIDataResultData";

export interface LoginCommandResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: LoginCommandResultIDataResultData;
}
