/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ReplyMessageDto } from "./replyMessageDto";

/**
 * @nullable
 */
export type MessageDtoRepliedToMessage = ReplyMessageDto | null;
