/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { MessageType } from "./messageType";
import type { ObjectId } from "./objectId";
import type { MessageDtoContent } from "./messageDtoContent";
import type { MessageDtoMedia } from "./messageDtoMedia";
import type { MessageStatus } from "./messageStatus";

export interface MessageDto {
  /** @nullable */
  readonly messageId?: string | null;
  messageType?: MessageType;
  /** @nullable */
  nickname?: string | null;
  senderId?: ObjectId;
  receiverId?: ObjectId;
  /** @nullable */
  content?: MessageDtoContent;
  /** @nullable */
  media?: MessageDtoMedia;
  messageStatus?: MessageStatus;
  repliedToMessage?: ObjectId;
  /** @nullable */
  readBy?: ObjectId[] | null;
}
