/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface MessageDeliveredCommandRequest {
  /** @nullable */
  chatId?: string | null;
  /** @nullable */
  messageId?: string | null;
}
