/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { MessageActionTime } from "./messageActionTime";
import type { MessageDtoContent } from "./messageDtoContent";
import type { MessageDtoFile } from "./messageDtoFile";
import type { MessageDtoRepliedToMessage } from "./messageDtoRepliedToMessage";
import type { MessageStatus } from "./messageStatus";
import type { MessageType } from "./messageType";

export interface MessageDto {
  /** @nullable */
  readonly messageId?: string | null;
  createdAt?: string;
  readonly messageStatus?: MessageStatus;
  /** @nullable */
  nickname?: string | null;
  messageType?: MessageType;
  /** @nullable */
  senderUsername?: string | null;
  /** @nullable */
  content?: MessageDtoContent;
  /** @nullable */
  file?: MessageDtoFile;
  /** @nullable */
  repliedToMessage?: MessageDtoRepliedToMessage;
  /** @nullable */
  receivers?: string[] | null;
  /** @nullable */
  deliveredTo?: MessageActionTime[] | null;
  /** @nullable */
  readBy?: MessageActionTime[] | null;
}
