/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { MessageType } from "./messageType";
import type { MessageDtoContent } from "./messageDtoContent";
import type { MessageDtoFile } from "./messageDtoFile";
import type { MessageStatus } from "./messageStatus";

export interface MessageDto {
  /** @nullable */
  readonly messageId?: string | null;
  messageType?: MessageType;
  /** @nullable */
  nickname?: string | null;
  /** @nullable */
  senderUsername?: string | null;
  /** @nullable */
  receiverUsername?: string | null;
  /** @nullable */
  content?: MessageDtoContent;
  /** @nullable */
  file?: MessageDtoFile;
  messageStatus?: MessageStatus;
  /** @nullable */
  repliedToMessage?: string | null;
  /** @nullable */
  readBy?: string[] | null;
}
