/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { MessageDto } from "./messageDto";
import type { ResultMessage } from "./resultMessage";

export interface MessageDtoListPaginatedResult {
  success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  data?: MessageDto[] | null;
  pageNumber?: number;
  pageSize?: number;
  totalPages?: number;
  totalRecords?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
}
