/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { MessageFileFilePath } from "./messageFileFilePath";

export interface MessageFile {
  size?: number;
  /** @nullable */
  filePath?: MessageFileFilePath;
  /** @nullable */
  contentType?: string | null;
}
