/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface MessageSeenCommandRequest {
  /** @nullable */
  chatId?: string | null;
  /** @nullable */
  messageId?: string | null;
}
