/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { MessageContent } from "./messageContent";

/**
 * @nullable
 */
export type MessageFileFilePath = MessageContent | null;
