/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface ObjectId {
  readonly timestamp?: number;
  readonly creationTime?: string;
}
