/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccessToken } from "./accessToken";

/**
 * @nullable
 */
export type RefreshTokenCommandResultAccessToken = AccessToken | null;
