/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ResultMessage } from "./resultMessage";
import type { RefreshTokenCommandResultIDataResultData } from "./refreshTokenCommandResultIDataResultData";

export interface RefreshTokenCommandResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: RefreshTokenCommandResultIDataResultData;
}
