/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { RegisterCommandResultAccessToken } from "./registerCommandResultAccessToken";
import type { RegisterCommandResultAccount } from "./registerCommandResultAccount";

export interface RegisterCommandResult {
  /** @nullable */
  accessToken?: RegisterCommandResultAccessToken;
  /** @nullable */
  account?: RegisterCommandResultAccount;
  /** @nullable */
  licenseExpiryDate?: string | null;
  /** @nullable */
  securityPhrases?: string[] | null;
}
