/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { RegisterCommandResultIDataResultData } from "./registerCommandResultIDataResultData";

export interface RegisterCommandResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  readonly message?: string | null;
  /** @nullable */
  readonly data?: RegisterCommandResultIDataResultData;
}
