/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { RegisterCommandResult } from "./registerCommandResult";

/**
 * @nullable
 */
export type RegisterCommandResultIDataResultData = RegisterCommandResult | null;
