/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { RegisterCommandResultIDataResultData } from "./registerCommandResultIDataResultData";
import type { ResultMessage } from "./resultMessage";

export interface RegisterCommandResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: RegisterCommandResultIDataResultData;
}
