/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { AccountDto } from "./accountDto";

/**
 * @nullable
 */
export type RegisterCommandResultAccount = AccountDto | null;
