/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ReplyMessageDtoContent } from "./replyMessageDtoContent";
import type { ReplyMessageDtoFile } from "./replyMessageDtoFile";

export interface ReplyMessageDto {
  /** @nullable */
  readonly messageId?: string | null;
  createdAt?: string;
  /** @nullable */
  content?: ReplyMessageDtoContent;
  /** @nullable */
  file?: ReplyMessageDtoFile;
}
