/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface ResultMessage {
  /** @nullable */
  code?: string | null;
  /** @nullable */
  description?: string | null;
}
