/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { MessageFile } from "./messageFile";

/**
 * @nullable
 */
export type SendMessageCommandRequestFile = MessageFile | null;
