/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { MessageType } from "./messageType";
import type { SendMessageCommandRequestContent } from "./sendMessageCommandRequestContent";
import type { SendMessageCommandRequestFile } from "./sendMessageCommandRequestFile";

export interface SendMessageCommandRequest {
  /** @nullable */
  chatId?: string | null;
  messageType?: MessageType;
  /** @nullable */
  content?: SendMessageCommandRequestContent;
  /** @nullable */
  file?: SendMessageCommandRequestFile;
  /** @nullable */
  repliedToMessage?: string | null;
  /** @nullable */
  isEphemeral?: boolean | null;
  /** @nullable */
  expireAfterReadSeconds?: number | null;
  /** @nullable */
  createdAt?: string | null;
  /** @nullable */
  expireAt?: string | null;
}
