/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { SendNotificationCommandRequestData } from "./sendNotificationCommandRequestData";

export interface SendNotificationCommandRequest {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  data?: SendNotificationCommandRequestData;
  /** @nullable */
  deviceTokens?: string[] | null;
}
