/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { StatisticDecimalPoint } from "./statisticDecimalPoint";

export interface StatisticsDecimalResult {
  value?: number;
  growShrink?: number;
  /** @nullable */
  chartData?: StatisticDecimalPoint[] | null;
}
