/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { StatisticsDecimalResult } from "./statisticsDecimalResult";

/**
 * @nullable
 */
export type StatisticsDecimalResultIDataResultData =
  StatisticsDecimalResult | null;
