/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { StatisticDataPoint } from "./statisticDataPoint";

export interface StatisticsResult {
  value?: number;
  growShrink?: number;
  /** @nullable */
  chartData?: StatisticDataPoint[] | null;
}
