/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface StatisticDecimalPoint {
  /** @nullable */
  name?: string | null;
  value?: number;
}
