/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ResultMessage } from "./resultMessage";
import type { StatisticsDecimalResultIDataResultData } from "./statisticsDecimalResultIDataResultData";

export interface StatisticsDecimalResultIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: StatisticsDecimalResultIDataResultData;
}
