/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ResultMessage } from "./resultMessage";

export interface StringIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: string | null;
}
