/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { SubscriptionIDataResultData } from "./subscriptionIDataResultData";

export interface SubscriptionIDataResult {
  readonly success?: boolean;
  /** @nullable */
  readonly message?: string | null;
  /** @nullable */
  readonly data?: SubscriptionIDataResultData;
}
