/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ObjectId } from "./objectId";
import type { EntityStatus } from "./entityStatus";

export interface Subscription {
  id?: ObjectId;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  deletedAt?: string | null;
  status?: EntityStatus;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  description?: string | null;
  periodTime?: number;
  price?: number;
  /** @nullable */
  discountPercentage?: number | null;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  currencySymbol?: string | null;
  isFreeTrial?: boolean;
}
