/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { EntityStatus } from "./entityStatus";
import type { ObjectId } from "./objectId";
import type { SubscriptionDeletedBy } from "./subscriptionDeletedBy";
import type { SubscriptionUpdatedBy } from "./subscriptionUpdatedBy";

export interface Subscription {
  id?: ObjectId;
  createdAt?: string;
  createdBy?: ObjectId;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  updatedBy?: SubscriptionUpdatedBy;
  /** @nullable */
  deletedAt?: string | null;
  /** @nullable */
  deletedBy?: SubscriptionDeletedBy;
  status?: EntityStatus;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  description?: string | null;
  periodTime?: number;
  price?: number;
  /** @nullable */
  discountPercentage?: number | null;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  currencySymbol?: string | null;
  isFreeTrial?: boolean;
}
