/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { SubscriptionDto } from "./subscriptionDto";

export interface SubscriptionDtoListIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: string[] | null;
  /** @nullable */
  readonly data?: readonly SubscriptionDto[] | null;
}
