/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { Subscription } from "./subscription";

/**
 * @nullable
 */
export type SubscriptionIDataResultData = Subscription | null;
