/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ResultMessage } from "./resultMessage";

export interface SuccessResult {
  success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
}
