/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { TicketStatus } from "./ticketStatus";
import type { TicketMessagesDto } from "./ticketMessagesDto";

export interface TicketDetailDto {
  /** @nullable */
  readonly ticketId?: string | null;
  /** @nullable */
  ticketCode?: string | null;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  content?: string | null;
  ticketStatus?: TicketStatus;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  licenseCode?: string | null;
  /** @nullable */
  ticketMessages?: TicketMessagesDto[] | null;
}
