/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ResultMessage } from "./resultMessage";
import type { TicketDetailDtoIDataResultData } from "./ticketDetailDtoIDataResultData";

export interface TicketDetailDtoIDataResult {
  readonly success?: boolean;
  /** @nullable */
  messages?: ResultMessage[] | null;
  /** @nullable */
  readonly data?: TicketDetailDtoIDataResultData;
}
