/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { TicketDetailDto } from "./ticketDetailDto";

/**
 * @nullable
 */
export type TicketDetailDtoIDataResultData = TicketDetailDto | null;
