/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { TicketStatus } from "./ticketStatus";
import type { TicketMessageDto } from "./ticketMessageDto";

export interface TicketDetailDto {
  /** @nullable */
  readonly ticketId?: string | null;
  /** @nullable */
  ticketCode?: string | null;
  /** @nullable */
  subject?: string | null;
  ticketStatus?: TicketStatus;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  licenseCode?: string | null;
  createdAt?: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  ticketMessages?: TicketMessageDto[] | null;
}
