/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { TicketDto } from "./ticketDto";

export interface TicketDtoListIDataResult {
  readonly success?: boolean;
  /** @nullable */
  readonly message?: string | null;
  /** @nullable */
  readonly data?: readonly TicketDto[] | null;
}
