/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ObjectId } from "./objectId";

export interface TicketMessage {
  id?: ObjectId;
  accountId?: ObjectId;
  /** @nullable */
  content?: string | null;
  createdAt?: string;
}
