/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface TicketMessageDto {
  /** @nullable */
  username?: string | null;
  /** @nullable */
  content?: string | null;
  createdAt?: string;
  isMyMessage?: boolean;
}
