/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface TicketMessagesDto {
  /** @nullable */
  username?: string | null;
  /** @nullable */
  content?: string | null;
  createdAt?: string;
}
