/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { TicketStatus } from "./ticketStatus";

export interface TicketDto {
  /** @nullable */
  readonly ticketId?: string | null;
  /** @nullable */
  ticketCode?: string | null;
  /** @nullable */
  subject?: string | null;
  ticketStatus?: TicketStatus;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  licenseCode?: string | null;
  createdAt?: string;
}
