/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export type TicketStatus = (typeof TicketStatus)[keyof typeof TicketStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TicketStatus = {
  Open: "Open",
  Waiting: "Waiting",
  Closed: "Closed",
} as const;
