/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { EntityStatus } from "./entityStatus";
import type { ObjectId } from "./objectId";
import type { TicketMessage } from "./ticketMessage";
import type { TicketStatus } from "./ticketStatus";

export interface Ticket {
  id?: ObjectId;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  deletedAt?: string | null;
  status?: EntityStatus;
  /** @nullable */
  ticketCode?: string | null;
  accountId?: ObjectId;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  content?: string | null;
  ticketStatus?: TicketStatus;
  /** @nullable */
  messages?: TicketMessage[] | null;
}
