/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export type TimeFrame = (typeof TimeFrame)[keyof typeof TimeFrame];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeFrame = {
  Daily: "Daily",
  Weekly: "Weekly",
  Monthly: "Monthly",
  Yearly: "Yearly",
} as const;
