/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { ObjectId } from "./objectId";
import type { EntityStatus } from "./entityStatus";

export interface Translate {
  id?: ObjectId;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  deletedAt?: string | null;
  status?: EntityStatus;
  /** @nullable */
  language?: string | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  value?: string | null;
}
