/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface Transaction {
  /** @nullable */
  transactionIdx?: string | null;
  createdAt?: string;
  /** @nullable */
  deletedAt?: string | null;
}
