/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface UpdateSubscriptionCommandRequest {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  code?: string | null;
  periodTime?: number;
  price?: number;
  /** @nullable */
  discountPercentage?: number | null;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  currencySymbol?: string | null;
  isFreeTrial?: boolean;
}
