/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface UpdateContactCommandRequest {
  /** @nullable */
  nickname?: string | null;
  /** @nullable */
  username?: string | null;
}
