/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */
import type { UploadFileCommandResult } from "./uploadFileCommandResult";

/**
 * @nullable
 */
export type UploadFileCommandResultIDataResultData =
  UploadFileCommandResult | null;
