/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface UploadFileCommandResult {
  /** @nullable */
  fileName?: string | null;
  /** @nullable */
  fileUrl?: string | null;
  /** @nullable */
  contentType?: string | null;
  contentLength?: number;
}
