/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * MagicMessenger
 * OpenAPI spec version: v1
 */

export interface ValidateGoogleReceiptCommandRequest {
  /** @nullable */
  packageName?: string | null;
  /** @nullable */
  productId?: string | null;
  /** @nullable */
  purchaseToken?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  deviceId?: string | null;
}
